### ISSUE TITLE
Use an IDE like PyCharm to write the code instead of a text editor

### ISSUE THREAD

**Issue by beebus** [acbackens/AtBSwP#2]
![image](https://user-images.githubusercontent.com/3438663/216336103-9a41ce11-0a52-4153-a097-8a85ffcbba34.png)

After writing the code in PyCharm, using its auto-completion feature (and other features), you can still just copy and paste into the GitHub browser interface here, but it'll end up looking more "professional" or better formatted, etc.

There are also ways to integrate PyCharm and GitHub so you don't have to copy/paste.

**Comment by acbackens** [comment]
Chapter 4 is a .py file. Will do this from now on.
